# Generated by Django 3.1.7 on 2021-05-12 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharewithcare_app', '0002_auto_20210510_1035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rawname', models.CharField(max_length=40)),
                ('quantity', models.IntegerField(max_length=10)),
                ('image', models.URLField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Add2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intername', models.CharField(max_length=40)),
                ('quantity', models.IntegerField(max_length=10)),
                ('image', models.URLField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Add3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endname', models.CharField(max_length=40)),
                ('brandname', models.CharField(max_length=40)),
                ('price', models.IntegerField(max_length=10)),
                ('quantity', models.IntegerField(max_length=10)),
                ('image', models.URLField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
