# Generated by Django 3.1.7 on 2021-05-12 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharewithcare_app', '0003_add_add2_add3_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add',
            name='image',
            field=models.ImageField(blank=True, upload_to='users/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='add',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='add2',
            name='image',
            field=models.ImageField(blank=True, upload_to='users/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='add2',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='add3',
            name='image',
            field=models.ImageField(blank=True, upload_to='users/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='add3',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='add3',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
