# Generated by Django 3.1.7 on 2021-05-15 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharewithcare_app', '0008_pay'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryname', models.CharField(max_length=40)),
                ('numberofvarieties', models.IntegerField()),
                ('collage', models.ImageField(blank=True, upload_to='listofinterproducts/')),
            ],
        ),
    ]
