# Generated by Django 3.1.7 on 2021-05-17 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharewithcare_app', '0014_buttermodel_creammodel_curdmodel_gheemodel_paneermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='BestSellers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('quantity', models.IntegerField()),
                ('brand', models.CharField(max_length=40)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(blank=True, upload_to='bestsellers/')),
            ],
        ),
    ]
