# Generated by Django 3.1.5 on 2021-03-18 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0024_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=200)),
                ('rate', models.IntegerField(default=0)),
            ],
        ),
    ]
