# Generated by Django 3.1.5 on 2021-04-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0026_corporate_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='price',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
