# Generated by Django 3.1.5 on 2021-04-04 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0028_auto_20210404_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporate',
            name='photo',
            field=models.ImageField(default=0, upload_to='images/'),
        ),
    ]
